services:
  db:
    container_name: db
    image: docker.io/library/redis:8.2.1
    expose:
      - "6379"
    volumes:
      - ./db:/db:z
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    image: docker.io/library/node:24
    working_dir: /backend
    command: |
      sh -c '
      npm install
      npm run dev
      '
    expose:
      - "3000"

    volumes:
      - ./backend:/backend:z
    stdin_open: true
    tty: true

  frontend:
    container_name: frontend
    image: docker.io/library/node:24
    working_dir: /frontend
    command: |
      sh -c '
      npm install
      npm run dev -- --host
      '
    expose:
      - "5173"
      - "24678"
    volumes:
      - ./frontend:/frontend:z
    stdin_open: true
    tty: true

  proxy:
    container_name: proxy
    image: docker.io/library/nginx:1.29.1
    working_dir: /proxy
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - "8080:80"
      - "4443:443"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - FRONTEND_PORT=5173
      - BACKEND_PORT=3000
      - SSL_CERT_FILE=server.crt
      - SSL_KEY_FILE=server.key
    volumes:
      - ./proxy:/proxy:z
      - ./proxy/templates:/etc/nginx/templates:z
      - ./proxy/certs:/etc/nginx/ssl:z
      - ./proxy/logs:/var/log/nginx:z
    stdin_open: true
    tty: true
